<PlanItem>:
    username: ""

<FlaggedPlanScreen>:
    BoxLayout:
        orientation: 'vertical'
        Widget:
            size_hint: None, None
            height: app.notch_height + app.navdrawer_height

        BoxLayout:
            orientation: 'horizontal'
            ScrollView:
                id: container
                MDList:
                    id: plan_list
                    size_hint_y: None
                    spacing: dp(15)
